title: The Awesomest Title
author: allygator
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for github labs github pages with jekyll course.

# social links
twitter_username: @allygator58
github_username:  allygator

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
